# Generated by Django 4.1.5 on 2023-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_order_delivery_status_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
